version: '2.0'
services:
  first: 
    build: ./a
    image: first
  second:
    build: ./b
    image: second
    depends_on: [ first ]
    ports:
      - "3892:3892"
    networks:
      - local
  third:
    build: ./c
    image: third
    depends_on: [ first ]
    ports:
      - "3893:3893"
    networks:
      - local
    extra_hosts:
      - "localhost:192.168.1.40"
networks:
  local:
    driver: bridge
    
    