version: '2.0'
services:
  first: 
    build: ./a
    image: first
  second:
    build: ./b
    image: second
    depends_on: [ first ]
    networks:
      - local
  third:
    build: ./c
    image: third
    depends_on: [ first ]
    ports:
      - "8080:3893"
    networks:
      - local
    volumes:
      - ./storage:/app/files
networks:
  local:
    driver: bridge
